# Generate random integers (1–100)

In [3]:
import numpy as np

In [7]:
a=np.random.randint(1,100,size=20)
print(a)

[88 14 73 99 51 11 18 69  1 25 17 73 70 71 58 80 47 20 28 31]


# Compute sum, mean, standard deviation.

In [11]:
a=np.array([1,2,3,4,5,6])
print(np.sum(a))
print(np.mean(a))
print(np.std(a))

21
3.5
1.707825127659933


# Create an identity matrix with eye().

In [14]:
a=np.eye(4,4,dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]



# Generate 5 random integers between 1 and 20.

In [19]:
a=np.random.randint(1,100,size=5)
print(a)

[84 17 25 51 49]



# Create a 5×5 random integer matrix and find its mean and standard deviation.


In [29]:
a=np.random.randint(1,100,(5,5))
print(a)
print('standerd devetion',np.std(a))

[[58 55 84  2 68]
 [77 18 31 40 21]
 [49 61 60 57 73]
 [80 75 91 79 94]
 [52 68 85 18 28]]
standerd devetion 24.948715397791528


# Find the most frequent number in a random array of 100 integers (0–10).

In [42]:
ar=np.random.randint(1,10,size=100)
print(ar)
value,count=np.unique(ar,return_counts=True)
m=value[np.argmax(count)]
f=count.max()
print(m)
print(f)

[2 7 5 5 5 3 2 5 3 3 1 5 5 8 9 9 5 8 5 8 1 5 8 7 2 7 9 4 8 3 8 4 4 3 5 3 7
 4 5 8 5 6 2 8 3 2 5 7 2 8 9 6 3 5 9 5 9 2 8 9 8 8 8 9 5 7 8 4 2 4 6 2 9 9
 7 9 7 6 9 6 4 3 4 9 5 9 6 2 1 3 9 1 1 1 9 1 3 1 5 6]
5
18


# Normalize a 4×4 random integer array (scale values between 0 and 1).


In [47]:
ary=np.random.randint(1,10,(4,4))
print(ary)
norm_arr = (ary-ary.min())/(ary.max()-ary.min())
print(norm_arr)

[[4 9 8 7]
 [7 1 5 3]
 [6 9 4 8]
 [8 2 6 9]]
[[0.375 1.    0.875 0.75 ]
 [0.75  0.    0.5   0.25 ]
 [0.625 1.    0.375 0.875]
 [0.875 0.125 0.625 1.   ]]


# Create two random 3×3 matrices and perform matrix multiplication.

In [54]:
a=np.random.randint(1,20,(3,3))
b=np.random.randint(1,20,(3,3))
print(a,b)
c=np.matmul(a,b)
print('multiplication\n',c)

[[10 14  1]
 [ 9  6  6]
 [15 19  7]] [[ 6 14  9]
 [ 5 15  6]
 [ 1 18  4]]
multiplication
 [[131 368 178]
 [ 90 324 141]
 [192 621 277]]
